local M = {}

M.VALIDATION_STATE_OK = 0
M.VALIDATION_STATE_INVALID = -1
M.VALIDATION_STATE_TAKEN = -2

M.LOGIN_SUCCESS = 1
M.LOGIN_BAD_CREDENTIALS = -10

M.ENV_PRODUCTION = 1
M.ENV_DEVELOPMENT = 2
M.ENV_TESTING = 3
M.ENV_STAGING = 4
M.ENV_INVALID = -1

-- Load paths
M.CONFIG_ROOT = os.getenv('CONFIG_ROOT') or '/etc/foxcaves'
M.LUA_ROOT = os.getenv('LUA_ROOT')
M.FRONTEND_ROOT = os.getenv('FRONTEND_ROOT')
M.MODULE_ROOT = M.LUA_ROOT .. '/modules'

return M
