name: Test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: https://data.forgejo.org/actions/checkout@v6
      - name: Update Docker version
        uses: https://github.com/docker/setup-docker-action@v4
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        with:
          channel: stable
          github-token: ${{ secrets.EXT_GITHUB_TOKEN }}
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Log in to Docker Registry
        uses: https://data.forgejo.org/docker/login-action@v3
        with:
          registry: git.foxden.network
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: https://data.forgejo.org/docker/setup-buildx-action@v3
      - name: Set up Node.js
        uses: https://data.forgejo.org/actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true
          token: ${{ secrets.EXT_GITHUB_TOKEN }}
      - uses: https://github.com/cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.EXT_GITHUB_TOKEN }}
      - name: Build container image
        run: |
          nix build .#foxcaves-docker
          docker load -i result
      - name: Symlink foxcaves app
        run: nix build .#foxcaves
      # Run tests
      - name: Add to hostsfile
        run: sudo bash -c "echo '127.0.0.1 app.foxcaves cdn.foxcaves' >> /etc/hosts"
      - name: Run test container
        run: docker compose -f docker-compose.yml -f docker-compose.testing.yml up -d --remove-orphans
      - name: Run some basic tests
        run: |
          set -ex
          HTTP_GET='curl -XGET -m 5 -s -f'
          timeout 30s bash -c "until $HTTP_GET http://app.foxcaves:8080/readyz; do sleep 1; done" || true
          timeout 30s bash -c "until $HTTP_GET http://app.foxcaves:8080/healthz; do sleep 1; done" || true
          $HTTP_GET -I http://app.foxcaves:8080/files
          $HTTP_GET -I http://app.foxcaves:8080/api/v1/system/info
          [ "$($HTTP_GET http://app.foxcaves:8080/api/v1/system/info | jq -r .release)" == "${{ github.sha }}" ]
      - name: Prepare tests
        working-directory: ./frontend
        run: npm ci && npx playwright install chromium --with-deps
      - name: Run tests
        working-directory: ./frontend
        run: |
          source ../result/bin/foxcaves-env
          npm test
      - name: Test container teardown
        if: always()
        run: |
          docker compose -f docker-compose.yml -f docker-compose.testing.yml logs
          docker compose -f docker-compose.yml -f docker-compose.testing.yml down
      # - name: Test results upload
      #   uses: actions/upload-artifact@v5
      #   if: always()
      #   with:
      #     name: playwright-test-results
      #     path: frontend/test-results/
