local M = {}
setfenv(1, M)

VALIDATION_STATE_OK = 0
VALIDATION_STATE_INVALID = -1
VALIDATION_STATE_TAKEN = -2

LOGIN_SUCCESS = 1
LOGIN_USER_INACTIVE = 0
LOGIN_USER_BANNED = -1
LOGIN_BAD_CREDENTIALS = -10

ENV_PRODUCTION = 1
ENV_DEVELOPMENT = 2
ENV_TESTING = 3
ENV_STAGING = 4
ENV_INVALID = -1

return M
