ALTER TABLE users ADD COLUMN totp_secret VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ALTER COLUMN totp_secret DROP DEFAULT;
ALTER TABLE users ADD COLUMN totp_enabled INT NOT NULL DEFAULT 0;
ALTER TABLE users ALTER COLUMN totp_enabled DROP DEFAULT;
