#!/bin/sh
set -e

mkdir -p /var/www/foxcaves/tmp /var/www/foxcaves/storage
chown www-data:www-data /var/www/foxcaves/tmp /var/www/foxcaves/storage

rm -f /etc/nginx/listener.conf
ln -s "/etc/nginx/listener.$ENVIRONMENT.conf" /etc/nginx/listener.conf

exec /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/custom.conf
