#!/bin/sh

mkdir -p /var/www/foxcaves/tmp/thumbs /var/www/foxcaves/tmp/files
chown www-data:www-data /var/www/foxcaves/tmp/thumbs /var/www/foxcaves/tmp/files /var/www/foxcaves/storage

exec /usr/local/openresty/nginx/sbin/nginx -g 'daemon off; user www-data;'
