#!/bin/sh
set -e

mkdir -p /run/postgresql
chown postgres:postgres /run/postgresql
mkdir -p /var/lib/postgresql/data
chown postgres:postgres /var/lib/postgresql/data
chmod 0700 /var/lib/postgresql/data

if [ ! -f /var/lib/postgresql/data/postgresql.conf ]
then
    runuser -u postgres -- /usr/bin/initdb -D /var/lib/postgresql/data
fi

exec runuser -u postgres -- /usr/bin/postgres -D /var/lib/postgresql/data
