#!/bin/sh
set -e

# Initialize DDNS cron if needed
echo '#!/bin/sh' > /etc/periodic/15min/dyndns
if [ ! -z "${DDNS_URL_IPV4:-}" ]
then
    echo "/usr/bin/curl -s -m 60 -4 '$DDNS_URL_IPV4' > /dev/null" >> /etc/periodic/15min/dyndns
fi
if [ ! -z "${DDNS_URL_IPV6:-}" ]
then
    echo "/usr/bin/curl -s -m 60 -6 '$DDNS_URL_IPV6' > /dev/null" >> /etc/periodic/15min/dyndns
fi
chmod +x /etc/periodic/15min/dyndns

if [ ! -z "${DDNS_URL_IPV4:-}" ]
then
    /usr/bin/curl -m 5 -4 "$DDNS_URL_IPV4" || true
fi
if [ ! -z "${DDNS_URL_IPV6:-}" ]
then
    /usr/bin/curl -m 5 -6 "$DDNS_URL_IPV6" || true
fi

exec crond -f
