#!/bin/sh
set -e

mkdir -p /var/www/foxcaves/tmp /var/www/foxcaves/storage
chown foxcaves:foxcaves /var/www/foxcaves/tmp /var/www/foxcaves/storage

luajit /var/www/foxcaves/lua/nginx_configure.lua

exec /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/custom.conf
