#!/bin/sh
set -e

mkdir -p /var/www/foxcaves/tmp /var/www/foxcaves/storage /etc/resty-auto-ssl
chown foxcaves:foxcaves /var/www/foxcaves/tmp /var/www/foxcaves/storage /etc/resty-auto-ssl

luajit /var/www/foxcaves/lua/nginx_configure.lua

exec /usr/local/openresty/bin/openresty -c /usr/local/openresty/nginx/conf/custom.conf
