#!/bin/sh
set -e

export CAPTCHA_FONT=/usr/share/fonts/opensans/OpenSans-Regular.ttf

mkdir -p /var/www/foxcaves/tmp /var/www/foxcaves/storage /etc/resty-auto-ssl
chown foxcaves:foxcaves /var/www/foxcaves/tmp /var/www/foxcaves/storage /etc/resty-auto-ssl

luajit /var/www/foxcaves/lua/nginx_configure.lua

rm -f /run/nginx-lua-api.sock

exec /usr/local/openresty/bin/openresty -c /usr/local/openresty/nginx/conf/custom.conf
