name: Lint lua code
on: [push]
- uses: nebularg/actions-luacheck@v1
  with:
    path: backend
    annotate: error
- uses: nebularg/actions-luacheck@v1
  with:
    path: frontend/luahtml
    annotate: error
