name: Run tests

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call: {}

jobs:
  frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: frontend
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: frontend
          eslint_extensions: ts,tsx
          prettier: true
          prettier_dir: frontend/src
  backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Lint backend
        uses: nebularg/actions-luacheck@v1
        with:
          path: backend
          annotate: error
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: backend
      - name: Run prettier
        run: npm run lint:prettier
        working-directory: backend
