name: Lint lua code
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Lint backend
        uses: nebularg/actions-luacheck@v1
        with:
          path: backend
          annotate: error
      - name: Lint frontend/luahtml
        uses: nebularg/actions-luacheck@v1
        with:
          path: frontend/luahtml
          annotate: error
