name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group: {}
  workflow_call: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Lint backend
        uses: nebularg/actions-luacheck@v1
        with:
          path: backend
          annotate: error
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: frontend
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: frontend
          eslint_extensions: js,jsx,ts,tsx
          prettier: true
          prettier_dir: frontend/src
  e2etests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Add to hostsfile
        run: sudo bash -c "echo '127.0.0.1 main.foxcaves short.foxcaves' >> /etc/hosts"
      - name: Run test container
        run: docker-compose -f docker-compose.yml -f docker-compose.testing.yml up -d --build --remove-orphans
      - name: Run some basic tests
        run: |
          set -ex
          HTTP_GET='curl -XGET -m 5 -s -f -I'
          timeout 30s bash -c "until $HTTP_GET http://main.foxcaves:8080/api/v1/system/info; do sleep 1; done" || true
          $HTTP_GET http://main.foxcaves:8080/files
          $HTTP_GET http://main.foxcaves:8080/api/v1/system/info
      - name: Prepare browser tests
        run: |
          set -ex
          cd frontend
          npm ci
          npx playwright install chromium --with-deps
          npx playwright test
      - name: Run browser tests
        run: npx playwright test
      - name: Test container teardown
        if: always()
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.testing.yml logs site
          docker-compose -f docker-compose.yml -f docker-compose.testing.yml down
